### ISSUE TITLE
Example ey.yml snippets to be code blocks

### ISSUE THREAD

**Issue by drnic** [engineyard/ey-docs#112]
On http://docs.engineyard.com/customize-your-deployment.html, in section "Using ey.yml to customize your deployment ", instead of  `environments: myapp_staging: copy_exclude: - .git` I think it should be:

``` yaml
environments:
    myapp_staging:
      copy_exclude:
        - .git
```

This issue is in 3 places within this section.

The HTML looks ok, but the parent tag should be a &lt;pre> or a &lt;code> perhaps so it keeps its YAML structure?
